import csv
import os
import datetime

# --- 基礎配置 ---
DOMAIN = "mobsp.qzz.io"
REPO_URL = "https://github.com/mobsp/mobsp.github.io/blob/main"
CSV_FILE = 'Ⲙ𝔬ⲃⳝ𝔭_Indexer_Report.csv'
OUTPUT_FILE = 'README.md'

# --- 品牌美化地圖 ---
PRETTY_MAP = {
    "app": "📢 品牌導覽與公告 (Portal & News)",
    "blog": "✍️ 核心內容頻道 (Primary Channels)",
    "music": "🎵 音樂頻道 (Music Channel)",
    "shorts": "📱 短影音頻道 (Shorts)",
    "sup": "🤝 支援與服務 (Support Center)",
    "his": "📜 品牌時光軸 (History Log)",
    "tol": "🔧 核心工具庫 (Core Tools)",
    "tol/lab": "🧪 實驗室與開發 (Lab)",
    "tol/publisher": "📑 內容發布中心 (Publisher)",
    "tol/tourl": "🔗 短網址轉換 (URL Tools)",
    "tol/ve": "🎬 影音編輯工具 (Video Editor)",
    "set": "⚙️ 系統設定中心 (Settings)",
    "ROOT": "🏠 品牌根目錄"
}

def generate_full_index():
    if not os.path.exists(CSV_FILE):
        print(f"❌ 找不到數據源 {CSV_FILE}")
        return

    # 分類存儲字典
    portal_links = {} # 僅存放 HTML 任意門
    all_files_index = {} # 存放所有檔案的 3 種連結

    # 1. 解析 CSV
    with open(CSV_FILE, mode='r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            # 嚴格鎖定 main 分支
            if row['Branch'] == 'main':
                folder = row['Folder']
                path = row['Path']
                title = PRETTY_MAP.get(folder, f"📂 資源分區: {folder}")
                
                # 初始化分類
                if title not in portal_links: portal_links[title] = []
                if title not in all_files_index: all_files_index[title] = []

                # --- 樣式 A: 任意門 (僅限 HTML) ---
                if path.endswith('.html'):
                    clean_web_url = f"https://{DOMAIN}/{path.replace('index.html', '')}"
                    portal_links[title].append(f"| **{os.path.basename(path)}** | [✨ 點擊傳送]({clean_web_url}) |")

                # --- 樣式 B: 完整 3 種連結索引 (所有檔案) ---
                repo_link = f"{REPO_URL}/{path}"
                prod_link = f"https://{DOMAIN}/{path}"
                index_row = f"| `{path}` | [查看源碼]({repo_link}) | [正式網址]({prod_link}) |"
                all_files_index[title].append(index_row)

    # 2. 構建 Markdown 內容
    now = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    content = [
        f"# 🚪 Ⲙ𝔬ⲃⳝ𝔭 品牌總匯任意門",
        f"> 🕒 自動化更新：`{now}` (UTC+8) | 🌐 域名：`{DOMAIN}`",
        "\n---",
        "## 🧭 網站快速導覽 (Anywhere Door)",
        "這裡僅列出可直接訪問的網頁入口。\n"
    ]

    # 寫入任意門部分
    for title in portal_links:
        if portal_links[title]:
            content.append(f"### {title}")
            content.append("| 頁面名稱 | 任意門入口 |\n| :--- | :--- |")
            content.extend(portal_links[title])
            content.append("\n")

    content.append("---\n## 📂 全站檔案完整索引 (Full File Index)")
    content.append("此處包含儲存庫內所有檔案的相對路徑、GitHub 原始碼以及正式連結。\n")

    # 寫入全檔案索引部分
    for title in all_files_index:
        if all_files_index[title]:
            content.append(f"#### {title}")
            content.append("| 相對路徑 | 儲存庫原始碼 | 網站正式連結 |\n| :--- | :--- | :--- |")
            content.extend(all_files_index[title])
            content.append("\n")

    content.append("---\n*Generated by GitHub Pages 緹緹 - 您的全自動索引秘書*")

    # 3. 輸出
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write("\n".join(content))
    print(f"✅ 雙效索引已成功生成至 {OUTPUT_FILE}")

if __name__ == "__main__":
    generate_full_index()
