import csv
import os
import datetime

# --- 基礎配置 ---
DOMAIN = "mobsp.qzz.io"
REPO_URL = "https://github.com/mobsp/mobsp.github.io/blob/main"
CSV_FILE = 'Ⲙ𝔬ⲃⳝ𝔭_Indexer_Report.csv'
OUTPUT_FILE = 'README.md'

# --- 品牌美化地圖：定義分類標題與 Emoji ---
PRETTY_MAP = {
    "app": "📢 品牌導覽與公告 (Portal & News)",
    "blog": "✍️ 核心內容頻道 (Primary Channels)",
    "music": "🎵 音樂頻道 (Music Channel)",
    "shorts": "📱 短影音頻道 (Shorts)",
    "sup": "🤝 支援與服務 (Support Center)",
    "his": "📜 品牌時光軸 (History Log)",
    "tol": "🔧 核心工具庫 (Core Tools)",
    "tol/lab": "🧪 實驗室與開發 (Lab)",
    "tol/publisher": "📑 內容發布中心 (Publisher)",
    "tol/tourl": "🔗 短網址轉換 (URL Tools)",
    "tol/ve": "🎬 影音編輯工具 (Video Editor)",
    "set": "⚙️ 系統設定中心 (Settings)",
    "ROOT": "🏠 品牌根目錄"
}

def generate_full_system():
    if not os.path.exists(CSV_FILE):
        print(f"❌ 找不到報表檔案：{CSV_FILE}")
        return

    portal_sections = {}  # 存放 HTML 任意門連結
    file_index_sections = {}  # 存放所有檔案的詳細索引

    # 1. 解析 CSV 數據
    with open(CSV_FILE, mode='r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            # 僅處理 main 分支的資料
            if row['Branch'] == 'main':
                folder = row['Folder']
                path = row['Path']
                title = PRETTY_MAP.get(folder, f"📂 資源分區: {folder}")

                # 初始化字典分類
                if title not in portal_sections: portal_sections[title] = []
                if title not in file_index_sections: file_index_sections[title] = []

                # --- 樣式 A：品牌任意門 (僅限 HTML 頁面) ---
                if path.endswith('.html'):
                    # 移除 index.html 讓連結更美觀
                    web_link = f"https://{DOMAIN}/{path.replace('index.html', '')}"
                    portal_sections[title].append(f"| **{os.path.basename(path)}** | [🚪 點擊進入]({web_link}) |")

                # --- 樣式 B：全檔案三合一索引 (包含所有檔案類型) ---
                repo_path = f"{REPO_URL}/{path}"
                direct_url = f"https://{DOMAIN}/{path}"
                index_line = f"| `{path}` | [查看源碼]({repo_path}) | [連結]({direct_url}) |"
                file_index_sections[title].append(index_line)

    # 2. 構建 README 內容
    now = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    content = [
        f"# 🚪 Ⲙ𝔬ⲃⳝ𝔭 品牌總匯任意門",
        f"> **全站自動化索引系統** | 🕒 更新：`{now}`",
        "\n---",
        "## 🧭 快速導覽 (Portal)",
        "點擊下方門禁進入網頁版。 \n"
    ]

    # 寫入任意門部分
    for title, links in portal_sections.items():
        if links:
            content.append(f"### {title}")
            content.append("| 頁面名稱 | 傳送門入口 |\n| :--- | :--- |")
            content.extend(links)
            content.append("")

    content.append("\n---")
    content.append("## 📂 全站檔案完整索引 (Full Index)")
    content.append("包含儲存庫內所有檔案的相對路徑與三種訪問連結。\n")

    # 寫入完整索引部分
    for title, lines in file_index_sections.items():
        if lines:
            content.append(f"#### {title}")
            content.append("| 檔案相對路徑 | 原始碼連結 | 網站正式路徑 |\n| :--- | :--- | :--- |")
            content.extend(lines)
            content.append("")

    content.append("\n---")
    content.append("*Generated by Ⲙ𝔬ⲃⳝ𝔭 Auto-Indexer System*")

    # 3. 寫入檔案
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write("\n".join(content))
    
    print(f"✅ README.md 已成功生成，包含任意門與完整索引。")

if __name__ == "__main__":
    generate_full_system()
